apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome</title>
    </head>
    <body>
        <h1>Hello from Nginx!</h1>
        <p>This page is served by Nginx configured with ConfigMap.</br>
        This is the part of SMM home work "Kube configs of applications".</p>
    </body>
    </html>
  nginx-port: "80"
  multitool-port: "8080"
